sbs_commandes:
    resource: "@SBSCommandesBundle/Resources/config/routing.yml"
    prefix:   /

sbs_adminstration:
    resource: "@SBSAdminstrationBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
